// <auto-generated />
using Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230630104719_initials")]
    partial class initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Models.Record", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Company = "IBM",
                            Name = "Ankur",
                            Project = "Payroll",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            ID = 2,
                            Company = "IBM",
                            Name = "Akash",
                            Project = "Chat Bot",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            ID = 3,
                            Company = "HP",
                            Name = "Priya",
                            Project = "VR Gaming",
                            Role = "Project Manager"
                        },
                        new
                        {
                            ID = 4,
                            Company = "Microsoft",
                            Name = "Asha",
                            Project = "Payroll",
                            Role = "Solution Architect"
                        },
                        new
                        {
                            ID = 5,
                            Company = "HP",
                            Name = "Nandini",
                            Project = "Payroll",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            ID = 6,
                            Company = "Microsoft",
                            Name = "Piyush",
                            Project = "Payroll",
                            Role = "Delivery Manager"
                        },
                        new
                        {
                            ID = 7,
                            Company = "HP",
                            Name = "Ankur",
                            Project = "Chat Bot",
                            Role = "Lead Engineer"
                        },
                        new
                        {
                            ID = 8,
                            Company = "HP",
                            Name = "Akash",
                            Project = "VR Gaming",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            ID = 9,
                            Company = "IBM",
                            Name = "Priya",
                            Project = "Payroll",
                            Role = "Solution Architect"
                        },
                        new
                        {
                            ID = 10,
                            Company = "HP",
                            Name = "Asha",
                            Project = "Chat Bot",
                            Role = "Project Manager"
                        },
                        new
                        {
                            ID = 11,
                            Company = "HP",
                            Name = "Nandini",
                            Project = "VR Gaming",
                            Role = "Lead Engineer"
                        },
                        new
                        {
                            ID = 12,
                            Company = "Microsoft",
                            Name = "Piyush",
                            Project = "Chat Bot",
                            Role = "Delivery Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
